name: packages
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  http_parser: ^4.1.2
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  path: ^1.9.1
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  animations: ^2.1.0
  video_player: ^2.10.0
  intl: ^0.20.2
  uuid: ^4.5.1
  quick_actions: ^1.1.0
  get: ^4.7.2
  sensors_plus: ^7.0.0
  connectivity_plus: ^7.0.0
  animated_text_kit: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/mp4/
